### ISSUE TITLE
terminology: project or analysis?

### ISSUE THREAD

**Issue by magland** [flatironinstitute/stan-playground#54]
@jsoules @WardBrian 

We need to decide whether to use the term "project" or "analysis". I would vote for "analysis" to reserve "project" for a potentially larger entity such as a collection of analyses.

Thoughts?

**Comment by WardBrian** [comment]
I think I prefer “project”, and would vote for “workspace” if we eventually need a new noun for a larger collection

**Comment by magland** [comment]
> I think I prefer “project”, and would vote for “workspace” if we eventually need a new noun for a larger collection

I'm okay with that. @jsoules ?

**Comment by magland** [comment]
(if we do go with "project" then let's do that change at a later time once things stabilize)

**Comment by jsoules** [comment]
To be clear, we're looking for a term for the basic data object that includes a stan code file, sampling settings, data.json | data-generation.[py|R], and optional data-analysis.[py|R]?

I don't have strong feelings about this matter, but would probably go with "project" since that's what I'm used to seeing in the context of other multiple-file development setups.

Not too sure what a larger collection would consist of really--I'd probably still use "project" if we allowed multiple instances of models or data--but I'm also confident we can sort it out once we've described that use case more.

**Comment by magland** [comment]
Okay, seems like we agree on using "project" here.

Created #64 and closing.
